apiVersion: v1
kind: Namespace
metadata:
  name: karpenter-reserved-capacity-demo
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: capacity
  namespace: karpenter-reserved-capacity-demo
spec:
  replicas: 1
  type: AWSEKSNodeGroup
  id: ${NODE_GROUP_ARN}
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: capacity
  namespace: karpenter-reserved-capacity-demo
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: capacity
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - prometheus:
        query: karpenter_reserved_capacity_cpu_utilization{name="demo"}
        target:
          type: Utilization
          value: 60
    - prometheus:
        query: karpenter_reserved_capacity_memory_utilization{name="demo"}
        target:
          type: Utilization
          value: 60
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: demo
  namespace: karpenter-reserved-capacity-demo
spec:
  reservedCapacity:
    nodeSelector:
      eks.amazonaws.com/nodegroup: demo
