apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: queue-demo
spec:
  replicas: 1
  type: AWSEKSNodeGroup
  id: ${NODE_GROUP_ARN}
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: ${QUEUE_NAME}
spec:
  queue:
    type: AWSSQSQueue
    id: ${QUEUE_ARN}
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: node-autoscaler
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: queue-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - prometheus:
        query: karpenter_queue_length{name="${QUEUE_NAME}"}
        target:
          type: AverageValue
          value: 4 # One node per 4 messages
