apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: queue-processor-autoscaler
  namespace: karpenter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-processor
  minReplicas: 0
  maxReplicas: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - prometheus:
        query: karpenter_queue_length{name="$QUEUE_NAME"}
        target:
          type: AverageValue
          value: 1 # one message per pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-processor
  namespace: karpenter
spec:
  replicas: 0 # Will be scaled by autocaler
  selector:
    matchLabels:
      app: queue-processor
  template:
    metadata:
      labels:
        app: queue-processor
    spec:
      containers:
        - name: queue-processor
          image: ellistarn/debug
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-west-2"
            - name: AWS_DEFAULT_OUTPUT
              value: "json"
          command:
            - /bin/sh
            - -c
            - >
              while true ;
              do
              RECEIPT_HANDLE=$(aws sqs receive-message --queue-url $QUEUE_URL | jq -r '.Messages[0].ReceiptHandle') &&
              aws sqs delete-message --queue-url $QUEUE_URL --receipt-handle $RECEIPT_HANDLE &&
              sleep 30 ;
              done
          resources:
            requests:
              memory: 100Mi
              cpu: 1
